### ISSUE TITLE
Unable to disable the remedy-controller for already existing Shoot

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/gardener-extension-provider-azure#218] opened 2020-12-08 09:37 UTC
**How to categorize this issue?**

/kind bug
/priority normal
/platform azure

**What you expected to happen**:
remedy-controller to be removed when the Shoot is annotated with `azure.provider.extensions.gardener.cloud/disable-remedy-controller=true` and it is reconciled afterwards

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot

2. Ensure that the remedy-controller is present as expected

```
$ k -n shoot--dev--bar po -l app=remedy-controller-azure
NAME                                       READY   STATUS    RESTARTS   AGE
remedy-controller-azure-756f555b6b-g4h6s   1/1     Running   0          7h6m
```

3. Annotate the Shoot with `azure.provider.extensions.gardener.cloud/disable-remedy-controller=true` and then trigger a reconcile

```
$ k -n garden-dev annotate shoot bar azure.provider.extensions.gardener.cloud/disable-remedy-controller=true
$ k -n garden-dev annotate shoot bar gardener.cloud/operation=reconcile
```

4. Ensure that the remedy-controller is not removed

```
$ k -n shoot--dev--bar get po -l app=remedy-controller-azure
NAME                                       READY   STATUS    RESTARTS   AGE
remedy-controller-azure-756f555b6b-g4h6s   1/1     Running   0          7h11m
```

- Gardener version (if relevant):
- Extension version: v1.15.2
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Others:

**Comment by dkistner** [comment] 2021-12-03 09:54
@stoyanr Is this meanwhile completely fixed?
I see the corresponding pr are merged.

**Comment by elchead** [comment] 2022-10-14 12:58
The problem still persists. The annotation only works before the control plane is deployed.

The problem is that the reconciler only applies updates to the charts but does not delete the old resources. (I.e. the annotation only makes the reconciler not apply the remedy chart again).

A solution could be to deploy the charts as managed resources and let the annotation delete this resource.

**Closed** 2022-10-25 13:10 UTC
Labels: kind/bug, lifecycle/rotten, platform/azure, priority/3
